#! /usr/bin/env php
<?php declare(strict_types=1);

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Exception\RuntimeException;
use Task\ShowCommand;

require __DIR__.'/vendor/autoload.php';

$app = new Application('Task App', '1.0');

$app->add(new ShowCommand());

try {
    $app->run();
} catch (\Exception $e) {
    throw new RuntimeException('Problem starting application.', $e->getMessage());
}
